package migrations_test

import (
	"context"
	"database/sql"
	"database/sql/driver"
	"errors"
	"io"
	"reflect"
	"strings"
	"sync"
	"testing"

	"github.com/SennovE/qrafter/ddl"
	"github.com/SennovE/qrafter/dialect"
	"github.com/SennovE/qrafter/migrations"
)

var _ migrations.Introspector = migrations.PostgreSQL{}

func TestPostgreSQLReadDDL(t *testing.T) {
	db := newFakeSQLDB([]fakeResult{
		{
			columns: []string{"server_version_num"},
			rows:    [][]driver.Value{{int64(150000)}},
			args:    []driver.Value{},
		},
		{
			columns: []string{"nspname", "relname"},
			rows: [][]driver.Value{
				{"public", "orgs"},
				{"public", "users"},
			},
			args: []driver.Value{"public"},
		},
		{
			columns: []string{
				"nspname", "relname", "attnum", "attname", "format_type",
				"attnotnull", "default_expr", "attidentity", "attgenerated",
			},
			rows: [][]driver.Value{
				{"public", "orgs", int64(1), "id", "bigint", true, nil, "d", ""},
				{"public", "orgs", int64(2), "name", "text", true, nil, "", ""},
				{"public", "users", int64(1), "id", "bigint", true, nil, "d", ""},
				{"public", "users", int64(2), "email", "text", true, nil, "", ""},
				{"public", "users", int64(3), "org_id", "bigint", false, nil, "", ""},
				{"public", "users", int64(4), "created_at", "timestamp with time zone", true, "now()", "", ""},
			},
			args: []driver.Value{"public"},
		},
		{
			columns: []string{
				"nspname", "relname", "conname", "contype", "columns",
				"refschema", "reftable", "refcolumns", "confdeltype", "confupdtype", "check_expr",
			},
			rows: [][]driver.Value{
				{"public", "orgs", "orgs_pkey", "p", "id", "", "", "", "", "", ""},
				{"public", "users", "users_pkey", "p", "id", "", "", "", "", "", ""},
				{"public", "users", "users_email_key", "u", "email", "", "", "", "", "", ""},
				{"public", "users", "users_email_check", "c", "email", "", "", "", "", "", "email <> ''"},
				{"public", "users", "users_org_id_fkey", "f", "org_id", "public", "orgs", "id", "c", "a", ""},
			},
			args: []driver.Value{"public"},
		},
		{
			columns: []string{
				"nspname", "relname", "indexrelname", "amname", "indisunique",
				"predicate", "tablespace", "indnullsnotdistinct",
			},
			rows: [][]driver.Value{
				{"public", "users", "users_email_active_idx", "btree", true, "deleted_at IS NULL", "", false},
			},
			args: []driver.Value{"public"},
		},
		{
			columns: []string{"nspname", "relname", "indexrelname", "position", "is_key", "expression"},
			rows: [][]driver.Value{
				{"public", "users", "users_email_active_idx", int64(1), true, "email"},
			},
			args: []driver.Value{"public"},
		},
	})
	defer db.Close()

	statements, err := migrations.NewPostgreSQL().ReadDDL(context.Background(), db)
	if err != nil {
		t.Fatalf("ReadDDL() error = %v", err)
	}

	sqlText, err := statements.Render(dialect.PostgreSQL{})
	if err != nil {
		t.Fatalf("Render() error = %v", err)
	}

	want := `CREATE TABLE "orgs" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "name" TEXT NOT NULL,
    CONSTRAINT "orgs_pkey" PRIMARY KEY ("id")
);
CREATE TABLE "users" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "email" TEXT NOT NULL,
    "org_id" BIGINT,
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT "users_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "users_email_key" UNIQUE ("email"),
    CONSTRAINT "users_email_check" CHECK (email <> ''),
    CONSTRAINT "users_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "orgs" ("id") ON DELETE CASCADE
);
CREATE UNIQUE INDEX "users_email_active_idx" ON "users" USING btree (email) WHERE deleted_at IS NULL;
`
	if sqlText != want {
		t.Fatalf("rendered DDL:\n%s\nwant:\n%s", sqlText, want)
	}
}

func TestReadDDLUsesCommonIntrospector(t *testing.T) {
	statements, err := migrations.ReadDDL(context.Background(), nil, staticIntrospector{
		schema: migrations.Schema{
			Tables: []migrations.Table{
				{
					Name: "events",
					Columns: []migrations.Column{
						{Name: "id", Type: ddl.BigInt(), NotNull: true},
					},
				},
			},
		},
	})
	if err != nil {
		t.Fatalf("ReadDDL() error = %v", err)
	}

	sqlText, err := statements.Render(dialect.PostgreSQL{})
	if err != nil {
		t.Fatalf("Render() error = %v", err)
	}

	want := "CREATE TABLE \"events\" (\n    \"id\" BIGINT NOT NULL\n);\n"
	if sqlText != want {
		t.Fatalf("rendered DDL = %q, want %q", sqlText, want)
	}
}

type staticIntrospector struct {
	schema migrations.Schema
}

func (i staticIntrospector) ReadSchema(context.Context, migrations.Database) (migrations.Schema, error) {
	return i.schema, nil
}

type fakeResult struct {
	columns []string
	rows    [][]driver.Value
	args    []driver.Value
}

type fakeSQLState struct {
	mu      sync.Mutex
	results []fakeResult
	next    int
}

type fakeConnector struct {
	state *fakeSQLState
}

func newFakeSQLDB(results []fakeResult) *sql.DB {
	return sql.OpenDB(fakeConnector{
		state: &fakeSQLState{results: results},
	})
}

func (c fakeConnector) Connect(context.Context) (driver.Conn, error) {
	return &fakeConn{state: c.state}, nil
}

func (c fakeConnector) Driver() driver.Driver {
	return fakeDriver{}
}

type fakeDriver struct{}

func (fakeDriver) Open(string) (driver.Conn, error) {
	return nil, errors.New("fake driver requires OpenDB")
}

type fakeConn struct {
	state *fakeSQLState
}

func (c *fakeConn) QueryContext(_ context.Context, query string, args []driver.NamedValue) (driver.Rows, error) {
	c.state.mu.Lock()
	defer c.state.mu.Unlock()

	if c.state.next >= len(c.state.results) {
		return nil, errors.New("unexpected query: " + compactSQL(query))
	}

	result := c.state.results[c.state.next]
	c.state.next++

	gotArgs := make([]driver.Value, 0, len(args))
	for _, arg := range args {
		gotArgs = append(gotArgs, arg.Value)
	}
	if !reflect.DeepEqual(gotArgs, result.args) {
		return nil, errors.New("unexpected args for " + compactSQL(query))
	}

	return &fakeRows{columns: result.columns, rows: result.rows}, nil
}

func (c *fakeConn) Prepare(string) (driver.Stmt, error) {
	return nil, errors.New("prepare is not implemented")
}

func (c *fakeConn) Close() error {
	return nil
}

func (c *fakeConn) Begin() (driver.Tx, error) {
	return nil, errors.New("transactions are not implemented")
}

type fakeRows struct {
	columns []string
	rows    [][]driver.Value
	next    int
}

func (r *fakeRows) Columns() []string {
	return r.columns
}

func (r *fakeRows) Close() error {
	return nil
}

func (r *fakeRows) Next(dest []driver.Value) error {
	if r.next >= len(r.rows) {
		return io.EOF
	}
	copy(dest, r.rows[r.next])
	r.next++
	return nil
}

func compactSQL(query string) string {
	return strings.Join(strings.Fields(query), " ")
}
