package migrations

import (
	"sort"

	"github.com/SennovE/qrafter"
	"github.com/SennovE/qrafter/ddl"
	"github.com/SennovE/qrafter/dialect"
)

// Schema is a normalized database schema snapshot.
type Schema struct {
	Tables []Table
}

// RegisterTable appends the schema inferred from table config T to schema.
func RegisterTable[T qrafter.TableConfigProvider](schema *Schema, d dialect.Renderer) {
	newSchema := TableConfigToSchema[T](d)
	schema.Tables = append(schema.Tables, newSchema.Tables...)
}

// DDL converts the schema snapshot into ddl statements.
func (s Schema) DDL() ddl.Statements {
	statements := make(ddl.Statements, 0, len(s.Tables))
	for i := range s.Tables {
		statements = append(statements, s.Tables[i].CreateTable())
	}
	for i := range s.Tables {
		for j := range s.Tables[i].Indexes {
			statements = append(statements, s.Tables[i].Indexes[j].CreateIndex())
		}
	}
	return statements
}

// DDLStatements converts the schema snapshot into a plain ddl renderer list.
func (s Schema) DDLStatements() []ddl.Renderer {
	statements := s.DDL()
	return append([]ddl.Renderer(nil), statements...)
}

func (s *Schema) normalize() {
	sort.SliceStable(s.Tables, func(i, j int) bool {
		if s.Tables[i].Schema == s.Tables[j].Schema {
			return s.Tables[i].Name < s.Tables[j].Name
		}
		return s.Tables[i].Schema < s.Tables[j].Schema
	})
	for i := range s.Tables {
		s.Tables[i].normalize()
	}
}

// Table describes a database table.
type Table struct {
	Schema      string
	Name        string
	Columns     []Column
	Constraints []Constraint
	Indexes     []Index
}

// CreateTable converts the table snapshot into a ddl CREATE TABLE statement.
func (t *Table) CreateTable() ddl.CreateTableStmt {
	stmt := ddl.CreateTable(t.Name)
	for i := range t.Columns {
		stmt = stmt.Columns(t.Columns[i].ColumnDef())
	}
	for i := range t.Constraints {
		stmt = stmt.Constraints(t.Constraints[i].TableConstraint())
	}
	return stmt
}

func (t *Table) normalize() {
	sort.SliceStable(t.Columns, func(i, j int) bool {
		return t.Columns[i].Position < t.Columns[j].Position
	})
	sort.SliceStable(t.Constraints, func(i, j int) bool {
		left := constraintKindOrder(t.Constraints[i].Kind)
		right := constraintKindOrder(t.Constraints[j].Kind)
		if left == right {
			return t.Constraints[i].Name < t.Constraints[j].Name
		}
		return left < right
	})
	sort.SliceStable(t.Indexes, func(i, j int) bool {
		return t.Indexes[i].Name < t.Indexes[j].Name
	})
}

// IdentityKind describes a generated identity column mode.
type IdentityKind = ddl.IdentityKind

const (
	// IdentityNone means the column is not an identity column.
	IdentityNone = ddl.IdentityNone
	// IdentityAlways renders GENERATED ALWAYS AS IDENTITY.
	IdentityAlways = ddl.IdentityAlways
	// IdentityByDefault renders GENERATED BY DEFAULT AS IDENTITY.
	IdentityByDefault = ddl.IdentityByDefault
)

// GeneratedKind describes a generated column storage mode.
type GeneratedKind = ddl.GeneratedKind

const (
	// GeneratedNone means the column is not generated.
	GeneratedNone = ddl.GeneratedNone
	// GeneratedStored renders GENERATED ALWAYS AS (...) STORED.
	GeneratedStored = ddl.GeneratedStored
	// GeneratedVirtual renders GENERATED ALWAYS AS (...) VIRTUAL.
	GeneratedVirtual = ddl.GeneratedVirtual
)

// Column describes a table column.
type Column struct {
	Schema    string
	TableName string
	Position  int
	Name      string
	Type      ddl.Type

	// DatabaseType is the type name returned by database introspection.
	DatabaseType string

	NotNull bool

	HasDefault  bool
	DefaultExpr string

	Identity IdentityKind

	Generated     GeneratedKind
	GeneratedExpr string
}

// ColumnDef converts the column snapshot into a ddl column definition.
func (c *Column) ColumnDef() ddl.ColumnDef {
	column := ddl.Column(c.Name, c.ddlType())
	switch c.Identity {
	case IdentityAlways:
		column = column.IdentityAlways()
	case IdentityByDefault:
		column = column.IdentityByDefault()
	}
	switch c.Generated {
	case GeneratedStored:
		column = column.GeneratedStored(c.GeneratedExpr)
	case GeneratedVirtual:
		column = column.GeneratedVirtual(c.GeneratedExpr)
	}
	if c.NotNull {
		column = column.NotNull()
	}
	if c.HasDefault && c.Identity == IdentityNone && c.Generated == GeneratedNone {
		column = column.DefaultExpr(c.DefaultExpr)
	}
	return column
}

func (c *Column) ddlType() ddl.Type {
	if !c.Type.IsZero() {
		return c.Type
	}
	return ddl.SQLType(c.DatabaseType)
}

// ConstraintKind describes a table-level constraint type.
type ConstraintKind string

const (
	// ConstraintPrimaryKey is a PRIMARY KEY constraint.
	ConstraintPrimaryKey ConstraintKind = "primary_key"
	// ConstraintUnique is a UNIQUE constraint.
	ConstraintUnique ConstraintKind = "unique"
	// ConstraintCheck is a CHECK constraint.
	ConstraintCheck ConstraintKind = "check"
	// ConstraintForeignKey is a FOREIGN KEY constraint.
	ConstraintForeignKey ConstraintKind = "foreign_key"
)

// Reference describes a foreign-key target.
type Reference struct {
	Schema    string
	TableName string
	Columns   []string
}

// Constraint describes a table-level constraint.
type Constraint struct {
	Schema    string
	TableName string
	Name      string
	Kind      ConstraintKind
	Columns   []string

	CheckExpr string

	Reference Reference
	OnDelete  ddl.ReferenceAction
	OnUpdate  ddl.ReferenceAction
}

// TableConstraint converts the constraint snapshot into a ddl table constraint.
func (c *Constraint) TableConstraint() ddl.TableConstraint {
	switch c.Kind {
	case ConstraintPrimaryKey:
		constraint := ddl.PrimaryKey(c.Columns...)
		if c.Name != "" {
			return constraint.Named(c.Name)
		}
		return constraint
	case ConstraintUnique:
		constraint := ddl.Unique(c.Columns...)
		if c.Name != "" {
			return constraint.Named(c.Name)
		}
		return constraint
	case ConstraintCheck:
		constraint := ddl.Check(ddl.RawPred(c.CheckExpr))
		if c.Name != "" {
			return constraint.Named(c.Name)
		}
		return constraint
	case ConstraintForeignKey:
		constraint := ddl.ForeignKey(c.Columns...).References(c.Reference.TableName, c.Reference.Columns...)
		if c.OnDelete != "" && c.OnDelete != ddl.NoAction {
			constraint = constraint.OnDelete(c.OnDelete)
		}
		if c.OnUpdate != "" && c.OnUpdate != ddl.NoAction {
			constraint = constraint.OnUpdate(c.OnUpdate)
		}
		if c.Name != "" {
			return constraint.Named(c.Name)
		}
		return constraint
	default:
		panic("migrations: unsupported constraint kind " + string(c.Kind))
	}
}

func constraintKindOrder(kind ConstraintKind) int {
	switch kind {
	case ConstraintPrimaryKey:
		return 1
	case ConstraintUnique:
		return 2
	case ConstraintCheck:
		return 3
	case ConstraintForeignKey:
		return 4
	default:
		return 100
	}
}

// IndexKey describes one PostgreSQL index key expression.
type IndexKey struct {
	Expression string
}

// Index describes a non-constraint index.
type Index struct {
	Schema      string
	TableSchema string
	TableName   string
	Name        string

	Unique bool
	Method ddl.IndexMethod

	Keys    []IndexKey
	Include []string

	Predicate string

	Tablespace       string
	NullsNotDistinct bool
}

// CreateIndex converts the index snapshot into a ddl CREATE INDEX statement.
func (i *Index) CreateIndex() ddl.CreateIndexStmt {
	keys := make([]ddl.IndexKey, 0, len(i.Keys))
	for j := range i.Keys {
		keys = append(keys, ddl.Key(ddl.RawExpr(i.Keys[j].Expression)))
	}

	stmt := ddl.CreateIndex(i.Name).On(i.TableName, keys...)
	if i.Unique {
		stmt = stmt.Unique()
	}
	if i.Method != "" {
		stmt = stmt.Using(i.Method)
	}
	if len(i.Include) > 0 {
		include := make([]ddl.Expression, 0, len(i.Include))
		for j := range i.Include {
			include = append(include, ddl.RawExpr(i.Include[j]))
		}
		stmt = stmt.Include(include...)
	}
	if i.NullsNotDistinct {
		stmt = stmt.NullsNotDistinct()
	}
	if i.Tablespace != "" {
		stmt = stmt.Tablespace(i.Tablespace)
	}
	if i.Predicate != "" {
		stmt = stmt.Where(ddl.RawPred(i.Predicate))
	}
	return stmt
}
