package ddl

// ColumnDef describes a column inside CREATE TABLE or ALTER TABLE ADD COLUMN.
type ColumnDef struct {
	Name string
	Type Type

	IsPrimaryKey bool
	IsNotNull    bool
	IsUnique     bool

	Options *ColumnOptions
}

// ColumnOptions stores optional column clauses.
type ColumnOptions struct {
	Default    *ColumnDefault
	Identity   *ColumnIdentity
	Generated  *ColumnGenerated
	Checks     []ColumnCheck
	References *ColumnReferences
}

// IdentityKind describes a generated identity column mode.
type IdentityKind string

const (
	// IdentityNone means the column is not an identity column.
	IdentityNone IdentityKind = ""
	// IdentityAlways renders GENERATED ALWAYS AS IDENTITY.
	IdentityAlways IdentityKind = "always"
	// IdentityByDefault renders GENERATED BY DEFAULT AS IDENTITY.
	IdentityByDefault IdentityKind = "by_default"
)

// GeneratedKind describes a generated column storage mode.
type GeneratedKind string

const (
	// GeneratedNone means the column is not generated.
	GeneratedNone GeneratedKind = ""
	// GeneratedStored renders GENERATED ALWAYS AS (...) STORED.
	GeneratedStored GeneratedKind = "stored"
	// GeneratedVirtual renders GENERATED ALWAYS AS (...) VIRTUAL.
	GeneratedVirtual GeneratedKind = "virtual"
)

// ColumnDefault describes a column DEFAULT clause.
type ColumnDefault struct {
	IsExpr bool
	Value  any
	Expr   string
}

// ColumnIdentity describes a generated identity column clause.
type ColumnIdentity struct {
	Kind IdentityKind
}

// ColumnGenerated describes a generated column clause.
type ColumnGenerated struct {
	Kind GeneratedKind
	Expr string
}

// ColumnCheck describes a column-level CHECK clause.
type ColumnCheck struct {
	Expr string
}

// ColumnReferences describes a column-level REFERENCES clause.
type ColumnReferences struct {
	Table   string
	Columns []string
}

// Column creates a column definition. Name can be a string or qrafter.Column.
func Column(name string, typ Type) ColumnDef {
	return ColumnDef{
		Name: name,
		Type: typ,
	}
}

// PrimaryKey marks the column as a primary key.
// Inside CREATE TABLE it renders as a table-level constraint.
func (c ColumnDef) PrimaryKey() ColumnDef {
	c.IsPrimaryKey = true
	return c
}

// NotNull adds a NOT NULL constraint.
func (c ColumnDef) NotNull() ColumnDef {
	c.IsNotNull = true
	return c
}

// Null adds an explicit NULL marker.
func (c ColumnDef) Null() ColumnDef {
	c.IsNotNull = false
	return c
}

// Unique adds a UNIQUE constraint.
// Inside CREATE TABLE it renders as a table-level constraint.
func (c ColumnDef) Unique() ColumnDef {
	c.IsUnique = true
	return c
}

// Default adds a literal DEFAULT value rendered through the dialect.
func (c ColumnDef) Default(value any) ColumnDef {
	options := c.cloneOptions()
	options.Default = &ColumnDefault{Value: value}
	c.Options = options
	return c
}

// DefaultExpr adds a raw SQL DEFAULT expression.
func (c ColumnDef) DefaultExpr(expr string) ColumnDef {
	options := c.cloneOptions()
	options.Default = &ColumnDefault{IsExpr: true, Expr: expr}
	c.Options = options
	return c
}

// Identity marks the column as a generated identity column.
func (c ColumnDef) Identity(kind IdentityKind) ColumnDef {
	switch kind {
	case IdentityAlways, IdentityByDefault:
	default:
		panic("ddl: unsupported identity kind")
	}
	options := c.cloneOptions()
	options.Identity = &ColumnIdentity{Kind: kind}
	c.Options = options
	return c
}

// IdentityAlways marks the column as GENERATED ALWAYS AS IDENTITY.
func (c ColumnDef) IdentityAlways() ColumnDef {
	return c.Identity(IdentityAlways)
}

// IdentityByDefault marks the column as GENERATED BY DEFAULT AS IDENTITY.
func (c ColumnDef) IdentityByDefault() ColumnDef {
	return c.Identity(IdentityByDefault)
}

// Generated marks the column as a generated column.
func (c ColumnDef) Generated(kind GeneratedKind, expr string) ColumnDef {
	switch kind {
	case GeneratedStored, GeneratedVirtual:
	default:
		panic("ddl: unsupported generated column kind")
	}
	options := c.cloneOptions()
	options.Generated = &ColumnGenerated{Kind: kind, Expr: expr}
	c.Options = options
	return c
}

// GeneratedStored marks the column as GENERATED ALWAYS AS (...) STORED.
func (c ColumnDef) GeneratedStored(expr string) ColumnDef {
	return c.Generated(GeneratedStored, expr)
}

// GeneratedVirtual marks the column as GENERATED ALWAYS AS (...) VIRTUAL.
func (c ColumnDef) GeneratedVirtual(expr string) ColumnDef {
	return c.Generated(GeneratedVirtual, expr)
}

// Check adds a CHECK expression.
// Inside CREATE TABLE it renders as a table-level constraint.
func (c ColumnDef) Check(expr string) ColumnDef {
	options := c.cloneOptions()
	options.Checks = append(options.Checks, ColumnCheck{Expr: expr})
	c.Options = options
	return c
}

// References adds a foreign key reference.
// Inside CREATE TABLE it renders as a table-level constraint.
func (c ColumnDef) References(table string, columns ...string) ColumnDef {
	options := c.cloneOptions()
	options.References = &ColumnReferences{
		Table:   table,
		Columns: append([]string(nil), columns...),
	}
	c.Options = options
	return c
}

func (c ColumnDef) cloneOptions() *ColumnOptions {
	if c.Options == nil {
		return &ColumnOptions{}
	}
	options := *c.Options
	options.Checks = append([]ColumnCheck(nil), c.Options.Checks...)
	return &options
}
