package ddl

// ColumnDef describes a column inside CREATE TABLE or ALTER TABLE ADD COLUMN.
type ColumnDef struct {
	name string
	typ  Type

	primaryKey bool
	notNull    bool
	unique     bool

	options *columnOptions
}

type columnOptions struct {
	defaultValue *columnDefault
	identity     *columnIdentity
	generated    *columnGenerated
	checks       []columnCheck
	references   *columnReferences
}

// IdentityKind describes a generated identity column mode.
type IdentityKind string

const (
	// IdentityNone means the column is not an identity column.
	IdentityNone IdentityKind = ""
	// IdentityAlways renders GENERATED ALWAYS AS IDENTITY.
	IdentityAlways IdentityKind = "always"
	// IdentityByDefault renders GENERATED BY DEFAULT AS IDENTITY.
	IdentityByDefault IdentityKind = "by_default"
)

// GeneratedKind describes a generated column storage mode.
type GeneratedKind string

const (
	// GeneratedNone means the column is not generated.
	GeneratedNone GeneratedKind = ""
	// GeneratedStored renders GENERATED ALWAYS AS (...) STORED.
	GeneratedStored GeneratedKind = "stored"
	// GeneratedVirtual renders GENERATED ALWAYS AS (...) VIRTUAL.
	GeneratedVirtual GeneratedKind = "virtual"
)

type columnDefault struct {
	isExpr bool
	value  any
	expr   string
}

type columnIdentity struct {
	kind IdentityKind
}

type columnGenerated struct {
	kind GeneratedKind
	expr string
}

type columnCheck struct {
	expr string
}

type columnReferences struct {
	table   string
	columns []string
}

// Column creates a column definition. Name can be a string or qrafter.Column.
func Column(name string, typ Type) ColumnDef {
	return ColumnDef{
		name: name,
		typ:  typ,
	}
}

// PrimaryKey marks the column as a primary key.
// Inside CREATE TABLE it renders as a table-level constraint.
func (c ColumnDef) PrimaryKey() ColumnDef {
	c.primaryKey = true
	return c
}

// NotNull adds a NOT NULL constraint.
func (c ColumnDef) NotNull() ColumnDef {
	c.notNull = true
	return c
}

// Null adds an explicit NULL marker.
func (c ColumnDef) Null() ColumnDef {
	c.notNull = false
	return c
}

// Unique adds a UNIQUE constraint.
// Inside CREATE TABLE it renders as a table-level constraint.
func (c ColumnDef) Unique() ColumnDef {
	c.unique = true
	return c
}

// Default adds a literal DEFAULT value rendered through the dialect.
func (c ColumnDef) Default(value any) ColumnDef {
	options := c.cloneOptions()
	options.defaultValue = &columnDefault{value: value}
	c.options = options
	return c
}

// DefaultExpr adds a raw SQL DEFAULT expression.
func (c ColumnDef) DefaultExpr(expr string) ColumnDef {
	options := c.cloneOptions()
	options.defaultValue = &columnDefault{isExpr: true, expr: expr}
	c.options = options
	return c
}

// Identity marks the column as a generated identity column.
func (c ColumnDef) Identity(kind IdentityKind) ColumnDef {
	switch kind {
	case IdentityAlways, IdentityByDefault:
	default:
		panic("ddl: unsupported identity kind")
	}
	options := c.cloneOptions()
	options.identity = &columnIdentity{kind: kind}
	c.options = options
	return c
}

// IdentityAlways marks the column as GENERATED ALWAYS AS IDENTITY.
func (c ColumnDef) IdentityAlways() ColumnDef {
	return c.Identity(IdentityAlways)
}

// IdentityByDefault marks the column as GENERATED BY DEFAULT AS IDENTITY.
func (c ColumnDef) IdentityByDefault() ColumnDef {
	return c.Identity(IdentityByDefault)
}

// Generated marks the column as a generated column.
func (c ColumnDef) Generated(kind GeneratedKind, expr string) ColumnDef {
	switch kind {
	case GeneratedStored, GeneratedVirtual:
	default:
		panic("ddl: unsupported generated column kind")
	}
	options := c.cloneOptions()
	options.generated = &columnGenerated{kind: kind, expr: expr}
	c.options = options
	return c
}

// GeneratedStored marks the column as GENERATED ALWAYS AS (...) STORED.
func (c ColumnDef) GeneratedStored(expr string) ColumnDef {
	return c.Generated(GeneratedStored, expr)
}

// GeneratedVirtual marks the column as GENERATED ALWAYS AS (...) VIRTUAL.
func (c ColumnDef) GeneratedVirtual(expr string) ColumnDef {
	return c.Generated(GeneratedVirtual, expr)
}

// Check adds a CHECK expression.
// Inside CREATE TABLE it renders as a table-level constraint.
func (c ColumnDef) Check(expr string) ColumnDef {
	options := c.cloneOptions()
	options.checks = append(options.checks, columnCheck{expr: expr})
	c.options = options
	return c
}

// References adds a foreign key reference.
// Inside CREATE TABLE it renders as a table-level constraint.
func (c ColumnDef) References(table string, columns ...string) ColumnDef {
	options := c.cloneOptions()
	options.references = &columnReferences{
		table:   table,
		columns: columns,
	}
	c.options = options
	return c
}

func (c ColumnDef) cloneOptions() *columnOptions {
	if c.options == nil {
		return &columnOptions{}
	}
	options := *c.options
	options.checks = append([]columnCheck(nil), c.options.checks...)
	return &options
}
